AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Events REST API

Globals:
  Function:
    Runtime: python3.9
    Architectures: [arm64]
    Timeout: 10
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        TABLE_NAME: !Ref EventsTable
        BUCKET_NAME: !Ref ImagesBucket

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins: ['*']
        AllowMethods: [GET, POST, PUT, DELETE]
        AllowHeaders: ['content-type', 'authorization']
GetUploadUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get_upload_url/
      Handler: app.handler
      Events:
        GetUploadUrl:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /events/{id}/upload-url
            Method: POST
      Policies:
        - S3WritePolicy:
            BucketName: !Ref ImagesBucket
        - DynamoDBWritePolicy:
            TableName: !Ref EventsTable



  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: eventId
          AttributeType: S
      KeySchema:
        - AttributeName: eventId
          KeyType: HASH

  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CreateEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/create_event/
      Handler: app.handler
      Events:
        CreateEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /events
            Method: POST
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref EventsTable

  CreateEventLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${CreateEventFunction}"
      RetentionInDays: 7

  GetEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get_events/
      Handler: app.handler
      Events:
        GetEvents:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /events
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref EventsTable

  GetEventsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${GetEventsFunction}"
      RetentionInDays: 7

  GetEventByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get_event_by_id/
      Handler: app.handler
      Events:
        GetEventById:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /events/{id}
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref EventsTable

  GetEventByIdLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${GetEventByIdFunction}"
      RetentionInDays: 7

Outputs:
  ApiUrl:
    Description: HTTP API endpoint
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
